version: "3.9"

services:
  backend:
    image: elt-backend
    build: ./backend
    container_name: elt-backend
    ports:
      - "8080:8080"

  frontend:
    image: elt-frontend
    build: ./frontend
    container_name: elt-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
